### ISSUE TITLE
How do I connect the sensor with a computer?

### ISSUE THREAD

**Issue by londi** [bosch-engineering/off_highway_sensor_drivers#10]
Hi there
I want to connect a bosch radarsensor to my computer and using this ros2 library to read data from the sensor. What is the easiest way to connect via the 8-pin plug on the sensor?
thanks in advance 
Londi

**Comment by HabibHaider123** [comment]
Hello Londi,

- which radar sensor do you want to use? I guess the Radar OHW or General Purpose Radar (GPR). Normally you will also receive a Technical Documentation together with the sensor which describes the pinning layout of the 8-pin plug on the sensor. Have you received the Documentation?

- Connection to a computer (only for Radar OHW or GPR): Basically you can connect the CAN1 pins (CAN Low and High) on the 8-pin plug to a subD connector (Pin 2 and 7) and use a PCAN-to-USB Adapter to connect the sensor to a computer. After that you should be able to read the data from the sensors after starting the corresponding ROS2 nodes.
A PCAN to USB adapter can be found here : https://www.peak-system.com/PCAN-USB.199.0.html?&L=1

I hope that helps.

**Comment by rcp1-beg** [comment]
Closed due to inactivity.
