### ISSUE TITLE
Feature: composable nodes

### ISSUE THREAD

**Issue by Timple** [bosch-engineering/off_highway_sensor_drivers#6]
It would be nice if multiple drivers can be launched in a composable node together with `ros2_socketcan` for example.

Only changes required are these: https://docs.ros.org/en/iron/Tutorials/Intermediate/Writing-a-Composable-Node.html

Would you be willing to implement this or accept a PR which does this?

**Comment by rcp1-beg** [comment]
Hi @Timple,

we are already working internally on replacing the nodes with components. You can expect this feature to be available in the next few weeks.

**Comment by Timple** [comment]
Great!

**Comment by daniel4ohw** [comment]
Hi @Timple 
we are excited to announce that this feature is now available in version 0.6.0!

**Comment by daniel4ohw** [comment]
Hi @Timple 
we are excited to announce that this feature is now available in version 0.6.0!

**Comment by Timple** [comment]
Awesome!
